//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registerweb2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daftar
    {
        public int Id { get; set; }
        public string nama { get; set; }
        public string instansi { get; set; }
        public string ttl { get; set; }
        public Nullable<int> nik { get; set; }
        public string email { get; set; }
        public Nullable<int> no_hp { get; set; }
    }
}
